#!/bin/bash
if type docker &> /dev/null; then
  alias dkps="docker ps"
  alias dkpa="docker ps -a"
  alias dkpl="docker ps -l -q"

  alias dkip="docker inspect --format '{{ .NetworkSettings.IPAddress }}'"

  alias dkd="docker run -d"
  alias dki="docker run -it"

  alias dkex="docker exec -it"

  dkbu() { docker build -t=$1 .; }

  docker_alias() { alias | grep 'docker' | sed "s/^\([^=]*\)=\(.*\)/\1 => \2/"| sed "s/['|\']//g" | sort; }
fi
