#!/bin/bash

alias mkdir='mkdir -p'

alias ls='ls -hF --color=auto'
alias ll='ls -l'
alias lla='ls -la'
alias lsd='ls -dAFh --color=auto .[^.]*' # ls Dotfiles
alias lld='lsd -l'
alias lst='ls -hFtl --color=auto | grep $(date +%Y-%m-%d)' #ls Today

alias vi='vim'
alias view='vim -R'

alias grep='grep --color=auto'

alias be='bundle exec'
alias virtualenv2='virtualenv --python=/usr/bin/python2'

if [ ! -x /usr/bin/xsel ]; then
  sudo apt-get install -y xsel
fi
alias pbcopy='xsel --clipboard --input'
alias pbpaste='xsel --clipboard --output'
